property:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

property_api:
    resource: "@ApiBundle/Resources/config/api-routing.yml"
    type:     rest
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"