property_page:
    path: /
    defaults: { _controller: ApiBundle:Properties:index }

property_delete:
    path: /property/{id}/delete
    defaults: { _controller: ApiBundle:Properties:delete }

property_edit:
    path: /property/{id}/edit
    defaults: { _controller: ApiBundle:Properties:formEdit }

property_create:
    path: /create
    defaults: { _controller: ApiBundle:Properties:formCreate }

